import os
from pathlib import Path
from typing import List
from dataclasses import dataclass
from git import Repo as GitRepo, GitCommandError
from github import Github, GithubException

@dataclass
class RepoContext:
    name: str
    branch: str
    local_path: Path
    token: str

    def repo_url(self):
        return f"https://github.com/{self.name}.git"

    def auth_repo_url(self):
        return f"https://{self.token}@github.com/{self.name}.git"

class GitRepoClient:
    def __init__(self, log):
        self.log = log

    def checkout_branch(self, repo_context: RepoContext):
        path = repo_context.local_path
        if not path.exists():
            print(f"Cloning {repo_context.repo_url()} to {path}")
            git_repo = GitRepo.clone_from(repo_context.repo_url(), path)
        else:
            print(f"Using existing repo at {path}")
            git_repo = GitRepo(path)

        git_repo.remote().fetch()
        try:
            git_repo.git.checkout(repo_context.branch)
            git_repo.remote().pull()
        except GitCommandError:
            print(f"Branch {repo_context.branch} not found locally. Checking out from origin.")
            git_repo.git.checkout('-b', repo_context.branch, f'origin/{repo_context.branch}')

    def get_file_tree(self, repo_context: RepoContext) -> List[str]:
        repo = GitRepo(repo_context.local_path)
        return [str(path.relative_to(repo_context.local_path)) for path in repo_context.local_path.rglob('*') if path.is_file()]

    def read_file_content(self, repo_context: RepoContext, filename: str) -> str:
        path = repo_context.local_path / filename
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()

    def patch_file(self, repo_context: RepoContext, filename: str, new_content: str, commit_message: str):
        file_path = repo_context.local_path / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)

        repo = GitRepo(repo_context.local_path)
        repo.git.add(filename)
        repo.index.commit(commit_message)

    def push_changes(self, repo_context: RepoContext):
        repo = GitRepo(repo_context.local_path)
        origin = repo.remote()
        origin.set_url(repo_context.auth_repo_url())
        origin.push(refspec=f"{repo_context.branch}:{repo_context.branch}")

    def open_pr(self, repo_context: RepoContext, base: str = "main", title: str = "Automated PR", body: str = "Generated by script") -> str:
        github = Github(repo_context.token)
        gh_repo = github.get_repo(repo_context.full_name())
        try:
            pr = gh_repo.create_pull(
                title=title,
                body=body,
                head=repo_context.branch,
                base=base
            )
            return pr.html_url
        except GithubException as e:
            return f"Failed to create PR: {e}"
