import logging
import os
from pathlib import Path
from typing import List
from dataclasses import dataclass
from git import Repo as GitRepo, GitCommandError
from github import Github, GithubException
import shutil
from git.exc import InvalidGitRepositoryError, GitCommandError

from src.config import config


@dataclass
class RepoContext:
    name: str
    branch: str


class RepositoryClient:
    def __init__(self, log):
        self.log = log

    def checkout_branch(self, repo_context: RepoContext):
        path = self._get_local_path(repo_context.name)
        repo_url = self._get_repo_auth(repo_context.name)
        if path.exists():
            try:
                git_repo = GitRepo(path)
            except InvalidGitRepositoryError:
                print(f"Path {path} is not a git repo. Deleting and recloning...")
                shutil.rmtree(path)
                git_repo = GitRepo.clone_from(repo_url, path)
        else:
            print(f"Cloning {repo_url} to {path}")
            git_repo = GitRepo.clone_from(repo_url, path)

        git_repo.remote().fetch()
        try:
            git_repo.git.checkout(repo_context.branch)
            print(f"Checked out existing branch {repo_context.branch}")
        except GitCommandError:
            print(
                f"Branch {repo_context.branch} does not exist locally. Trying to create from origin."
            )
            remote_branches = [ref.name.split("/")[-1] for ref in git_repo.remote().refs]
            if repo_context.branch in remote_branches:
                git_repo.git.checkout("-b", repo_context.branch, f"origin/{repo_context.branch}")
            else:
                # Create from main if the remote branch doesn't exist
                default_branch = "main"  # or detect dynamically
                git_repo.git.checkout("-b", repo_context.branch, f"origin/{default_branch}")
                print(f"Created new branch {repo_context.branch} from {default_branch}")
                git_repo.remote().pull()

    def patch_file(
        self, repo_context: RepoContext, filename: str, new_content: str
    ):
        local_path = self._get_local_path(repo_context.name)
        file_path = local_path / filename
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(new_content)

    def make_commit(
        self, repo_context: RepoContext, commit_message: str, filename: str | None = None
    ):
        repo = GitRepo(self._get_local_path(repo_context.name))

        if filename:
            repo.git.add(filename)
        else:
            repo.git.add(all=True)

        repo.index.commit(commit_message)

    def push_changes(self, repo_context: RepoContext):
        repo = GitRepo(self._get_local_path(repo_context.name))
        origin = repo.remote()
        origin.set_url(self._get_repo_auth(repo_context.name))
        origin.push(refspec=f"{repo_context.branch}:{repo_context.branch}")

    def open_pr(
        self,
        repo_context: RepoContext,
        base: str = "main",
        title: str = "Automated PR",
        body: str = "Generated by script",
    ) -> str:
        github = Github(config.github_api_key)
        gh_repo = github.get_repo(repo_context.name)

        try:
            existing_prs = gh_repo.get_pulls(state="open", base=base)
            for pr in existing_prs:
                if pr.head.ref == repo_context.branch:
                    print(f"Existing PR found: {pr.html_url}")
                    return pr.html_url

            # If none found, create a new PR
            pr = gh_repo.create_pull(title=title, body=body, head=repo_context.branch, base=base)
            print(f"New PR created: {pr.html_url}")
            return pr.html_url

        except GithubException as e:
            return f"Failed to create PR: {e}"

    def _get_repo_auth(self, repo_name):
        return f"https://{config.github_api_key}@github.com/{repo_name}.git"

    def _get_local_path(self, repo_name):
        return config.workspace_path / repo_name
